# Generated by Django 3.0.8 on 2020-07-24 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200724_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emails',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.EmailValidator('Email address is not valid')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
