# Generated by Django 3.0.8 on 2020-07-24 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200724_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(0)]),
        ),
    ]
